# Generated by Django 5.0.2 on 2024-03-04 07:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient_recipie_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipie_image_file_path),
        ),
    ]
